{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import uuid\n",
    "from IPython.display import display_javascript, display_html, display\n",
    "import json\n",
    "\n",
    "class RenderJSON(object):\n",
    "    def __init__(self, json_data):\n",
    "        if isinstance(json_data, dict):\n",
    "            self.json_str = json.dumps(json_data)\n",
    "        else:\n",
    "            self.json_str = json_data\n",
    "        self.uuid = str(uuid.uuid4())\n",
    "\n",
    "    def _ipython_display_(self):\n",
    "        display_html('<div id=\"{}\" style=\"height: 600px; width:100%;\"></div>'.format(self.uuid), raw=True)\n",
    "        display_javascript(\"\"\"\n",
    "        require([\"https://rawgit.com/caldwell/renderjson/master/renderjson.js\"], function() {\n",
    "        document.getElementById('%s').appendChild(renderjson(%s))\n",
    "        });\n",
    "        \"\"\" % (self.uuid, self.json_str), raw=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "from src.surquest.utils.appstoreconnect.credentials import Credentials\n",
    "from src.surquest.utils.appstoreconnect.analyticsreports.client import Client\n",
    "from src.surquest.utils.appstoreconnect.analyticsreports.enums.category import Category\n",
    "from src.surquest.utils.appstoreconnect.analyticsreports.enums.granularity import Granularity\n",
    "from pathlib import Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'eyJhbGciOiJFUzI1NiIsImtpZCI6IjVXRFVWM1VTQVUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiI2OWE2ZGU4MC1mZDQ0LTQ3ZTMtZTA1My01YjhjN2MxMWE0ZDEiLCJpYXQiOjE3NTM3NjE2NDMsImV4cCI6MTc1MzgwNDg0MywiYXVkIjoiYXBwc3RvcmVjb25uZWN0LXYxIn0.a49JIwyV6KToP1aZlHtqVP-Cf4iOjAGvGsMiWzp_J42RajnRWsnXPkWWNtb5ZNvIcrRhVTxNLZrw7Yno4roTQA'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "key_path = Path.cwd() / \"credentials\" / \"key.p8\"\n",
    "private_key = key_path.read_text()\n",
    "\n",
    "ISSUER_ID = \"69a6de80-fd44-47e3-e053-5b8c7c11a4d1\"\n",
    "KEY_ID = \"5WDUV3USAU\"\n",
    "APP_ID = \"6451202232\"\n",
    "CATEGORY = Category.APP_USAGE\n",
    "REPORT_NAME = \"App Store Installation and Deletion Detailed\"\n",
    "GRANULARITY = Granularity.DAILY\n",
    "DATE = \"2025-07-27\"\n",
    "\n",
    "\n",
    "credentials = Credentials(\n",
    "    issuer_id=ISSUER_ID, # 36-character issuer ID\n",
    "    key_id=KEY_ID, # 10-character key ID from App Store Connect\n",
    "    private_key=private_key\n",
    ")\n",
    "client = Client(credentials=credentials)\n",
    "credentials.generate_token(expiration_minutes=360)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "HTTP Error: 401 - {\n",
      "\t\"errors\": [{\n",
      "\t\t\"status\": \"401\",\n",
      "\t\t\"code\": \"NOT_AUTHORIZED\",\n",
      "\t\t\"title\": \"Authentication credentials are missing or invalid.\",\n",
      "\t\t\"detail\": \"Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens\"\n",
      "\t}]\n",
      "}\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'get'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[4]\u001b[39m\u001b[32m, line 3\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;66;03m#1A Read Report Requests\u001b[39;00m\n\u001b[32m      2\u001b[39m report_requests = client.read_report_requests(app_id=APP_ID)\n\u001b[32m----> \u001b[39m\u001b[32m3\u001b[39m report_request_id = \u001b[43mreport_requests\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget\u001b[49m(\u001b[33m\"\u001b[39m\u001b[33mdata\u001b[39m\u001b[33m\"\u001b[39m)[\u001b[32m0\u001b[39m].get(\u001b[33m\"\u001b[39m\u001b[33mid\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m      4\u001b[39m RenderJSON(report_requests)\n",
      "\u001b[31mAttributeError\u001b[39m: 'NoneType' object has no attribute 'get'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Bad pipe message: %s [b' 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Sa']\n",
      "Bad pipe message: %s [b'ri/537.36\\r\\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/', b'ng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\\r\\nAccept-Encoding: gzip, deflate, br, zstd\\r\\nA']\n",
      "Bad pipe message: %s [b'ept-Language: en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7,ru;q=0.6\\r\\nPriority: u=0, i\\r\\nReferer: https://stu', b'o.firebase.google.com/\\r\\nSec-Ch-Ua: \"Not)A;Brand\";v=\"8\", \"Chromium\";v=\"138\", \"Google Chrome\";v=\"138\"', b'Sec-Ch-Ua-Ar']\n",
      "Bad pipe message: %s [b': \"x86\"\\r\\nSec-Ch-Ua-Bitness: \"64\"\\r\\nSec-Ch-Ua-Form-Factors: \"Desktop\"\\r\\nSec-Ch-Ua-Full-Version: \"138.']\n",
      "Bad pipe message: %s [b'7204.169\"\\r\\nSec-Ch-Ua-Full-Version-List: \"Not)A;']\n",
      "Bad pipe message: %s [b'and\";v=\"8.0.0.0\", \"Chromium\";v=\"138.0.7204.169\", \"Google Chrome\";']\n",
      "Bad pipe message: %s [b'\"138.0.7204.169\"\\r\\nSec-Ch-Ua-Mobile: ?0\\r\\nSec-Ch-Ua-Model: \"\"\\r\\nSec-Ch-Ua-Platform: \"Windows\"\\r\\nSec-Ch-Ua-Platform-Versio', b' \"19.0.0\"\\r\\nSec-Ch-Ua-Wow64: ?0\\r\\nSec-Fetch-Dest: iframe\\r\\nSec-Fetch-Mode: navigate\\r\\nSec-Fetch-Site: cross-site\\r']\n",
      "Bad pipe message: %s [b'ec-Fetch-', b'orage-Access: active\\r\\nSec-Fetch-User: ?1\\r\\nSec-User-Ip: 10.20.20.206\\r\\nUpgrade-Insec']\n",
      "Bad pipe message: %s [b'e-Requests: 1\\r\\nX-Forwarded-Host: 33739-firebase-analytics-reports-1753781098444.cluster-ombtxv25tbd6yrjpp3lukp6zhc.c']\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n",
      "ERROR:tornado.general:Uncaught exception in ZMQStream callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py\", line 565, in _log_error\n",
      "    f.result()\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 299, in dispatch_control\n",
      "    await self.process_control(msg)\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 305, in process_control\n",
      "    idents, msg = self.session.feed_identities(msg, copy=False)\n",
      "                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"/home/user/python-appstoreconnect-analyticsreports/.venv/lib/python3.12/site-packages/jupyter_client/session.py\", line 994, in feed_identities\n",
      "    raise ValueError(msg)\n",
      "ValueError: DELIM not in msg_list\n"
     ]
    }
   ],
   "source": [
    "#1A Read Report Requests\n",
    "report_requests = client.read_report_requests(app_id=APP_ID)\n",
    "report_request_id = report_requests.get(\"data\")[0].get(\"id\")\n",
    "RenderJSON(report_requests)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#2A Read Report\n",
    "report = client.read_report_for_specific_request(\n",
    "    request_id=report_request_id,\n",
    "    params={\n",
    "        \"filter[category]\": CATEGORY.value,\n",
    "        \"filter[name]\": REPORT_NAME\n",
    "    }\n",
    ")\n",
    "\n",
    "report_id = report.get(\"data\")[0].get(\"id\")\n",
    "print(report_id)\n",
    "RenderJSON(report)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#3A Read Report Instances\n",
    "instances = client.read_list_of_instances_of_report(\n",
    "    report_id=report_id,\n",
    "    params={\n",
    "        \"filter[granularity]\": GRANULARITY.value,\n",
    "        \"filter[processingDate]\": DATE\n",
    "    }\n",
    ")\n",
    "instance_id = instances.get(\"data\")[0].get(\"id\")\n",
    "RenderJSON(instances)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#4 Get segments\n",
    "segments = client.read_segments_for_report(\n",
    "    instance_id=instance_id\n",
    ")\n",
    "url  = segments.get(\"data\")[0].get(\"attributes\").get(\"url\")\n",
    "RenderJSON(segments)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Download the report data\n",
    "data = client.download_report_to_dicts(\n",
    "    report_url=url\n",
    ")\n",
    "data"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
